In [1]:
import pandas as pd

importamos dataset

In [ ]:
df = pd.read_csv('bookings.csv', sep= '^', error_bad_lines=False)

C:\Users\ORTEGA\Anaconda\lib\site-packages\IPython\core\interactiveshell.py:3063: DtypeWarning: Columns (7,8,27) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

Veamos que pinta tiene el dataset

In [5]:
df.head(3)

,act_date,source,pos_ctry,pos_iata,pos_oid,rloc,cre_date,duration,distance,dep_port,...,route,carrier,bkg_class,cab_class,brd_time,off_time,pax,year,month,oid
0,2013-03-05 00:00:00,1A,DE,a68dd7ae953c8acfb187a1af2dcbe123,1a11ae49fcbf545fd2afc1a24d88d2b7,ea65900e72d71f4626378e2ebd298267,2013-02-22 00:00:00,1708,0,ZRH,...,LHRZRH,VI,T,Y,2013-03-07 08:50:00,2013-03-07 11:33:37,-1.0,2013.0,3.0,NULL
1,2013-03-26 00:00:00,1A,US,e612b9eeeee6f17f42d9b0d3b79e75ca,7437560d8f276d6d05eeb806d9e7edee,737295a86982c941f1c2da9a46a14043,2013-03-26 00:00:00,135270,0,SAL,...,SALATLCLT,NV,L,Y,2013-04-12 13:04:00,2013-04-12 22:05:40,1.0,2013.0,3.0,NULL
2,2013-03-26 00:00:00,1A,US,e612b9eeeee6f17f42d9b0d3b79e75ca,7437560d8f276d6d05eeb806d9e7edee,737295a86982c941f1c2da9a46a14043,2013-03-26 00:00:00,135270,0,SAL,...,CLTATLSAL,NV,U,Y,2013-07-15 07:00:00,2013-07-15 11:34:51,1.0,2013.0,3.0,NULL

Comprobamos que el año en todos es 2013

In [6]:
df[df["year"] != 2013.0]

,act_date,source,pos_ctry,pos_iata,pos_oid,rloc,cre_date,duration,distance,dep_port,...,route,carrier,bkg_class,cab_class,brd_time,off_time,pax,year,month,oid
5000007,2013-03-25 00:00:00,1V JP,NaN,a37584d1485cb35991e4ff1a2ba92262,2013-03-25 00:00:00,8371,60,NRT,TYO,JP,...,2013-04-14 11:05:00,2013-04-14 17:10:56,2,2013,3,NULL,NaN,NaN,NaN,NaN

Ahora vamos a comprobar si hay nan en la columna de pax

In [8]:
df['pax'].value_counts()

 1.0     5032696
-1.0     2203551
 2.0     1185822
-2.0      630010
 3.0      262770
          ...
 64.0         10
-76.0         10
 66.0         10
-90.0         10
 51.0         10
Name: pax, Length: 124, dtype: int64

In [14]:
df[df['pax'] == df['pax'].isnull()]

Empty DataFrame
Columns: [act_date           , source, pos_ctry, pos_iata, pos_oid  , rloc          , cre_date           , duration, distance, dep_port, dep_city, dep_ctry, arr_port, arr_city, arr_ctry, lst_port, lst_city, lst_ctry, brd_port, brd_city, brd_ctry, off_port, off_city, off_ctry, mkt_port, mkt_city, mkt_ctry, intl, route          , carrier, bkg_class, cab_class, brd_time           , off_time           , pax, year, month, oid      ]
Index: []

[0 rows x 38 columns]

Veamos la info del df

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000010 entries, 0 to 10000009
Data columns (total 38 columns):
 #   Column               Dtype
---  ------               -----
 0   act_date             object
 1   source               object
 2   pos_ctry             object
 3   pos_iata             object
 4   pos_oid              object
 5   rloc                 object
 6   cre_date             object
 7   duration             object
 8   distance             object
 9   dep_port             object
 10  dep_city             object
 11  dep_ctry             object
 12  arr_port             object
 13  arr_city             object
 14  arr_ctry             object
 15  lst_port             object
 16  lst_city             object
 17  lst_ctry             object
 18  brd_port             object
 19  brd_city             object
 20  brd_ctry             object
 21  off_port             object
 22  off_city             object
 23  off_ctry             object
 24  mkt_port             object
 25  mkt_city             object
 26  mkt_ctry             object
 27  intl                 object
 28  route                object
 29  carrier              object
 30  bkg_class            object
 31  cab_class            object
 32  brd_time             object
 33  off_time             object
 34  pax                  float64
 35  year                 float64
 36  month                float64
 37  oid                  object
dtypes: float64(3), object(35)
memory usage: 2.8+ GB

Copio la database para no estropear el dataset original

In [18]:
book = df

Mi objetivo es anadir directamente una columna con la ciudad 

Pero me doy cuenta que el string tiene espacios en arr_port por lo tanto voy a crear una nueva columna con el nombre de iata con el codigo bien pueto

In [19]:
#Por fin he entendido el problema y es que el string esta mal el book^arr_port ya que tiene una separacion muy grande.
new = book["arr_port"].str.split(" ", n = 1, expand = True)

In [20]:
book["iata"] = new[0]

A continuacion importo nueva tabal con el iata code y el nombre de la ciudad

In [22]:
datas = pd.read_json('https://raw.githubusercontent.com/mwgg/Airports/master/airports.json') 
datas.head()

,00AK,00AL,00AZ,00CA,00CO,00FA,00FL,00GA,00ID,00IL,...,ZYMD,ZYMH,ZYQQ,ZYTH,ZYTL,ZYTN,ZYTX,ZYXC,ZYYJ,ZYYY
icao,00AK,00AL,00AZ,00CA,00CO,00FA,00FL,00GA,00ID,00IL,...,ZYMD,ZYMH,ZYQQ,ZYTH,ZYTL,ZYTN,ZYTX,ZYXC,ZYYJ,ZYYY
iata,,,,,,,,,,,...,MDG,OHE,NDG,,DLC,TNH,SHE,XEN,YNJ,
name,Lowell Field,Epps Airpark,Cordes Airport,Goldstone /Gts/ Airport,Cass Field,Grass Patch Airport,River Oak Airport,Lt World Airport,Delta Shores Airport,Hammer Airport,...,Mudanjiang Hailang International Airport,Gu-Lian Airport,Qiqihar Sanjiazi Airport,Tahe Airport,Zhoushuizi Airport,Tonghua Sanyuanpu Airport,Taoxian Airport,Xingcheng Air Base,Yanji Chaoyangchuan Airport,Shenyang Dongta Airport
city,Anchor Point,Harvest,Cordes,Barstow,Briggsdale,Bushnell,Okeechobee,Lithonia,Clark Fork,Polo,...,Mudanjiang,Mohe,Qiqihar,Tahe,Dalian,Tonghua,Shenyang,,Yanji,Shenyang
state,Alaska,Alabama,Arizona,California,Colorado,Florida,Florida,Georgia,Idaho,Illinois,...,Heilongjiang,Heilongjiang,Heilongjiang,Heilongjiang,Liaoning,Jilin,Liaoning,Liaoning,Jilin,Liaoning

Como quiero hacer un diccionario de las columnas (pd series) hago transpose

In [23]:
datas = datas.T
datas.head()

,icao,iata,name,city,state,country,elevation,lat,lon,tz
00AK,00AK,,Lowell Field,Anchor Point,Alaska,US,450,59.9492,-151.696,America/Anchorage
00AL,00AL,,Epps Airpark,Harvest,Alabama,US,820,34.8648,-86.7703,America/Chicago
00AZ,00AZ,,Cordes Airport,Cordes,Arizona,US,3810,34.3056,-112.165,America/Phoenix
00CA,00CA,,Goldstone /Gts/ Airport,Barstow,California,US,3038,35.3505,-116.888,America/Los_Angeles
00CO,00CO,,Cass Field,Briggsdale,Colorado,US,4830,40.6222,-104.344,America/Denver

De esta tabla voy a sacar un diccionario para luego mapear con el codigo iata y la ciudad

In [25]:

dicc = pd.Series(datas.city.values,index=datas.iata).to_dict()

dicc

{'': 'Shenyang',
 'ICY': 'Icy Bay',
 'HGZ': 'Hogatza',
 'BYW': 'Blakely Island',
 'BDF': 'Bradford',
 'BCS': 'Belle Chasse',
 'BWL': 'Blackwell',
 'DUF': 'Corolla',
 'FOB': 'Fort Bragg',
 'ALX': 'Alexander City',
 'AFT': 'Bila',
 'RNA': 'Arona',
 'ATD': 'Atoifi',
 'VEV': 'Barakoma',
 'BPF': 'Batuna Mission Station',
 'GEF': 'Liangia',
 'AKS': 'Auki',
 'BNY': 'Anua',
 'CHY': '',
 'BAS': 'Ballalae',
 'FRE': 'Fera Island',
 'HIR': 'Honiara',
 'MBU': 'Mbambanakira',
 'AVU': '',
 'IRA': 'Kirakira',
 'SCZ': 'Santa Cruz/Graciosa Bay/Luova',
 'MUA': '',
 'GZO': 'Gizo',
 'MNY': 'Stirling Island',
 'PRS': 'Parasi',
 'RNL': 'Rennell Island',
 'EGM': 'Sege',
 'NNB': 'Santa Ana Island',
 'RUS': 'Marau',
 'VAO': 'Suavanao',
 'XYA': 'Yandina',
 'KGE': 'Kagau Island',
 'KWS': 'Kwailabesi',
 'GTA': 'Gatokae',
 'RIN': 'Ringi Cove',
 'RBV': 'Ramata',
 'CEX': 'Chena Hot Springs',
 'HED': 'Herendeen Bay',
 'TWE': 'Taylor',
 'CDL': 'Candle',
 'BSZ': 'Egegik',
 'BSW': 'Boswell Bay',
 'INU': 'Yaren District',
 'ATP': 'Aitape',
 'AMU': 'Amanab',
 'ADC': 'Andekombe',
 'AIE': 'Aiome',
 'KPM': '',
 'AUJ': 'Ambunti',
 'AWB': 'Awaba',
 'AYU': 'Aiyura Valley',
 'VMU': 'Baimuru',
 'BDZ': '',
 'BUA': 'Buka Island',
 'OPU': 'Balimo',
 'BUL': 'Bulolo',
 'CMU': 'Kundiawa',
 'DER': 'Derim',
 'DAU': 'Daru',
 'XYR': 'Yellow River Mission',
 'FNE': 'Fane Mission',
 'FIN': 'Buki',
 'FAQ': 'Frieda River',
 'GKA': 'Goronka',
 'GRL': 'Au',
 'GAR': 'Garaina',
 'GUR': 'Gurney',
 'GAP': 'Gusap',
 'PNP': 'Popondetta',
 'GMI': 'Gasmata Island',
 'GVI': 'Green River',
 'HKN': 'Hoskins',
 'KIE': 'Kieta',
 'LSA': 'Losuia',
 'KBM': '',
 'KDR': 'Kandrian',
 'UNG': 'Kiunga',
 'KRI': 'Kikori',
 'KMA': 'Kerema',
 'KKD': 'Kokoda',
 'KZF': 'Kaintiba',
 'KUQ': 'Kuri',
 'KVG': 'Kavieng',
 'KWO': 'Kawito',
 'LNV': 'Londolovit',
 'LMY': 'Lake Murray',
 'LMI': 'Lumi',
 'MYX': 'Menyamya',
 'MAG': 'Madang',
 'HGU': 'Mount Hagen',
 'MXK': 'Mindik',
 'GUV': 'Mougulu',
 'MDU': '',
 'MAS': '',
 'MXH': 'Moro',
 'MIS': 'Misima Island',
 'GBF': 'Negarbo',
 'MFO': 'Manguna',
 'UKU': 'Nuku',
 'LAE': 'Nadzab',
 'OGE': '',
 'OSE': 'Omora',
 'PDI': 'Pindiu',
 'POM': 'Port Moresby',
 'KRJ': '',
 'RMN': '',
 'KMR': 'Karimui',
 'SBE': '',
 'NIS': 'Simberi Island',
 'SIL': 'Sila Mission',
 'SIM': 'Simbai',
 'SKC': 'Suki',
 'TIZ': 'Tari',
 'TBG': 'Tabubil',
 'TFM': 'Telefomin',
 'TPI': 'Tapini',
 'TAJ': 'Aitape',
 'RAB': 'Tokua',
 'TKW': 'Tekin',
 'TFI': 'Tufi',
 'VAI': '',
 'WAO': 'Wabo',
 'WBM': '',
 'AGL': '',
 'WWK': 'Wewak',
 'WOA': 'Wonenara',
 'WSU': 'Wasu',
 'WTP': 'Fatima Mission',
 'WUG': 'Wau',
 'JEG': 'Aasiaat',
 'UAK': 'Narsarsuaq',
 'CNP': 'Neerlerit Inaat',
 'GOH': 'Nuuk',
 'JAV': 'Ilulissat',
 'KUS': 'Kulusuk',
 'JSU': 'Maniitsoq',
 'JFR': 'Paamiut',
 'NAQ': 'Qaanaaq',
 'SFJ': 'Kangerlussuaq',
 'JHS': 'Sisimiut',
 'THU': 'Thule',
 'JUV': 'Upernavik',
 'JQA': 'Uummannaq',
 'AEY': 'Akureyri',
 'BIU': 'Bildudalur',
 'BGJ': 'Borgarfjordur eystri',
 'BJD': 'Bakkafjordur',
 'BLO': 'Blonduos',
 'BQD': 'Budardalur',
 'BXV': 'Breiddalsvik',
 'DJU': 'Djupivogur',
 'EGS': 'Egilsstadir',
 'FAS': 'Faskrudsfjordur',
 'FAG': 'Fagurholsmyri',
 'GUU': 'Grundarfjordur',
 'GJR': 'Gjogur',
 'GRY': 'Grimsey',
 'HVK': 'Holmavik',
 'HFN': 'Hornafjordur',
 'FLI': 'Flateyri',
 'HZK': 'Husavik',
 'HVM': 'Hvammstangi',
 'HLO': 'Onundarfjordur',
 'IFJ': 'Isafjordur',
 'KEF': 'Reykjavik',
 'OPA': 'Kopasker',
 'SAK': 'Saudarkrokur',
 'NOR': 'Nordfjordur',
 'OFJ': 'Olafsfjordur',
 'PFJ': 'Patreksfjordur',
 'RHA': 'Reykholar',
 'OLI': 'Rif',
 'RFN': 'Raufarhofn',
 'RKV': 'Reykjavik',
 'MVA': 'Myvatn',
 'SIJ': 'Siglufjordur',
 'SYK': 'Stykkisholmur',
 'TEY': 'Tingeyri',
 'THO': 'Thorshofn',
 'VEY': 'Vestmannaeyjar',
 'VPN': 'Vopnafjordur',
 'PRN': 'Prishtina',
 'YZZ': 'Trail',
 'YAA': 'Anahim Lake',
 'DGF': 'Douglas Lake',
 'JHL': 'Albian Village',
 'DUQ': 'Duncan',
 'YWM': 'Williams Harbour',
 'YFX': 'St. Lewis',
 'YHA': 'Port Hope Simpson',
 'YRG': 'Rigolet',
 'DVK': 'Diavik',
 'YCK': 'Colville Lake',
 'YLE': 'Whati',
 'NML': 'Fort McMurray',
 'ZSP': 'St. Paul',
 'DAS': 'Great Bear Lake',
 'YFI': 'Suncor Energy Site',
 'SUR': 'Summer Beaver',
 'YAX': 'Angling Lake',
 'WNN': 'Wunnumin Lake',
 'YNO': 'North Spirit Lake',
 'XBE': 'Bearskin Lake',
 'KIF': 'Kingfisher Lake',
 'YOG': 'Ogoki Post',
 'YEB': 'Bar River',
 'YHP': 'Poplar Hill',
 'YNX': 'Snap Lake',
 'YKU': 'Chisasibi',
 'ZTB': 'Tete-a-la-Baleine',
 'YAU': 'Kattiniq',
 'ZLT': 'La Tabatiere',
 'YAC': 'Cat Lake',
 'YAR': 'La Grande-3',
 'YAG': 'Fort Frances',
 'YAH': 'La Grande-4',
 'YAL': 'Alert Bay',
 'YAM': 'Sault Ste Marie',
 'XKS': 'Kasabonika',
 'YKG': 'Kangirsuk',
 'YAT': 'Attawapiskat',
 'YAW': 'Halifax',
 'YAY': 'St. Anthony',
 'YAZ': 'Tofino',
 'YBA': 'Banff',
 'YBB': 'Kugaaruk',
 'YBC': 'Baie-Comeau',
 'QBC': 'Bella Coola',
 'YBE': 'Uranium City',
 'YBY': 'Bonnyville',
 'YBG': 'Bagotville',
 'YBK': 'Baker Lake',
 'YBL': 'Campbell River',
 'XTL': 'Tadoule Lake',
 'YBR': 'Brandon',
 'YBT': 'Brochet',
 'YBV': 'Berens River',
 'YBX': 'Lourdes-De-Blanc-Sablon',
 'YRF': 'Cartwright',
 'YCB': 'Cambridge Bay',
 'YCC': 'Cornwall',
 'YCD': 'Nanaimo',
 'YCE': 'Centralia',
 'YCG': 'Castlegar',
 'YCH': 'Miramichi',
 'XCM': 'Chatham-Kent',
 'YCL': 'Charlo',
 'YCN': 'Cochrane',
 'YCO': 'Kugluktuk',
 'YCQ': 'Chetwynd',
 'YCR': 'Cross Lake',
 'YCS': 'Chesterfield Inlet',
 'YCY': 'Clyde River',
 'YCZ': 'Fairmont Hot Springs',
 'YDA': 'Dawson City',
 'YDB': 'Burwash',
 'YDF': 'Deer Lake',
 'YDM': 'Ross River',
 'YDN': 'Dauphin',
 'YDO': 'Dolbeau-St-Felicien',
 'YDP': 'Nain',
 'YDQ': 'Dawson Creek',
 'YEG': 'Edmonton',
 'YEK': 'Arviat',
 'YEL': 'Elliot Lake',
 'YEM': 'Manitowaning',
 'YEN': 'Estevan',
 'YER': 'Fort Severn',
 'YET': 'Edson',
 'YEU': 'Eureka',
 'YEV': 'Inuvik',
 'YEY': 'Amos',
 'YFA': 'Fort Albany',
 'YFB': 'Iqaluit',
 'YFC': 'Fredericton',
 'YFE': 'Forestville',
 'YFH': 'Fort Hope',
 'YTM': 'Riviere Rouge',
 'YFO': 'Flin Flon',
 'YFR': 'Fort Resolution',
 'YFS': 'Fort Simpson',
 'YMN': 'Makkovik',
 'YGB': 'Texada',
 'YGD': 'Goderich',
 'YGH': 'Fort Good Hope',
 'YGK': 'Kingston',
 'YGL': 'La Grande Riviere',
 'YGM': 'Gimli',
 'YGO': 'Gods Lake Narrows',
 'YGP': 'Gaspe',
 'YGQ': 'Geraldton',
 'YGR': 'Iles-de-la-Madeleine',
 'YGT': 'Igloolik',
 'YGV': 'Havre St-Pierre',
 'YGW': 'Kuujjuarapik',
 'YGX': 'Gillam',
 'YGZ': 'Grise Fiord',
 'YQC': 'Quaqtaq',
 'YHD': 'Dryden',
 'YHE': 'Hope',
 'YHF': 'Hearst',
 'YNS': 'Nemiscau',
 'YHI': 'Ulukhaktok',
 'YHK': 'Gjoa Haven',
 'YHM': 'Hamilton',
 'YHN': 'Hornepayne',
 'YHO': 'Hopedale',
 'YHR': 'Chevery',
 'YHT': 'Haines Junction',
 'YHU': 'Montreal',
 'YHY': 'Hay River',
 'YHZ': 'Halifax',
 'YIB': 'Atikokan',
 'YDG': 'Digby',
 'YIF': 'St-Augustin',
 'YIK': 'Ivujivik',
 'YIO': 'Pond Inlet',
 'YIV': 'Island Lake',
 'YJF': 'Fort Liard',
 'YJN': 'St Jean',
 'YJT': 'Stephenville',
 'YKA': 'Kamloops',
 'LAK': 'Aklavik',
 'YKF': 'Kitchener',
 'YKJ': 'Key Lake',
 'YKL': 'Schefferville',
 'AKV': 'Akulivik',
 'YKQ': 'Waskaganish',
 'YKX': 'Kirkland Lake',
 'YKY': 'Kindersley',
 'YKZ': 'Toronto',
 'YPJ': 'Aupaluk',
 'YLC': 'Kimmirut',
 'YLD': 'Chapleau',
 'YLH': 'Lansdowne House',
 'YLJ': 'Meadow Lake',
 'YSG': "Lutselk'e",
 'YLL': 'Lloydminster',
 'YLR': 'Leaf Rapids',
 'YLK': 'Barrie-Orillia',
 'YLT': 'Alert',
 'XGR': 'Kangiqsualujjuaq',
 'YLW': 'Kelowna',
 'YMA': 'Mayo',
 'YME': 'Matane',
 'YMG': 'Manitouwadge',
 'YMH': "Mary's Harbour",
 'YMJ': 'Moose Jaw',
 'YML': 'Charlevoix',
 'YMM': 'Fort McMurray',
 'YMO': 'Moosonee',
 'YMT': 'Chibougamau',
 'YUD': 'Umiujaq',
 'YMX': 'Montreal',
 'YNA': 'Natashquan',
 'YNC': 'Wemindji',
 'YND': 'Gatineau',
 'YNE': 'Norway House',
 'YNL': 'Points North Landing',
 'YNM': 'Matagami',
 'YNN': 'Nejanilini Lake',
 'HZP': 'Fort Mackay',
 'YOA': 'Ekati',
 'YOC': 'Old Crow',
 'YOD': 'Cold Lake',
 'YOH': 'Oxford House',
 'YOJ': 'High Level',
 'YOO': 'Oshawa',
 'YOP': 'Rainbow Lake',
 'YOS': 'Owen Sound',
 'YOW': 'Ottawa',
 'YPA': 'Prince Albert',
 'YPC': 'Paulatuk',
 'YPS': 'Port Hawkesbury',
 'YPE': 'Peace River',
 'YPG': 'Portage',
 'YPH': 'Inukjuak',
 'YPL': 'Pickle Lake',
 'YPM': 'Pikangikum',
 'YPN': 'Port-Menier',
 'YPO': 'Peawanuck',
 'YPQ': 'Peterborough',
 'YPR': 'Prince Rupert',
 'YPW': 'Powell River',
 'YPX': 'Puvirnituq',
 'YPY': 'Fort Chipewyan',
 'YQA': 'Muskoka',
 'YQB': 'Quebec',
 'YQD': 'The Pas',
 'YQF': 'Red Deer',
 'YQG': 'Windsor',
 'YQH': 'Watson Lake',
 'YQI': 'Yarmouth',
 'YQK': 'Kenora',
 'YQL': 'Lethbridge',
 'YQM': 'Moncton',
 'YQN': 'Nakina',
 'YQQ': 'Comox',
 'YQR': 'Regina',
 'YQS': 'St Thomas',
 'YQT': 'Thunder Bay',
 'YQU': 'Grande Prairie',
 'YQV': 'Yorkton',
 'YQW': 'North Battleford',
 'YQX': 'Gander',
 'YQY': 'Sydney',
 'YQZ': 'Quesnel',
 'YRA': 'Gameti',
 'YRB': 'Resolute Bay',
 'YRI': 'Riviere-du-Loup',
 'YRJ': 'Roberval',
 'YRL': 'Red Lake',
 'YRO': 'Ottawa',
 'YRP': 'Carp',
 'YRQ': 'Trois-Rivieres',
 'YRS': 'Red Sucker Lake',
 'YRT': 'Rankin Inlet',
 'YRV': 'Revelstoke',
 'YSB': 'Sudbury',
 'YSC': 'Sherbrooke',
 'YSF': 'Stony Rapids',
 'YSH': 'Smiths Falls',
 'YSJ': 'Saint John',
 'YSK': 'Sanikiluaq',
 'YSL': 'St Leonard',
 'YSM': 'Fort Smith',
 'YCM': 'St Catharines',
 'YSP': 'Marathon',
 'YST': 'St. Theresa Point',
 'YSU': 'Summerside',
 'YSY': 'Sachs Harbour',
 'YTA': 'Pembroke',
 'YTE': 'Cape Dorset',
 'YTF': 'Alma',
 'YTH': 'Thompson',
 'YTL': 'Big Trout Lake',
 'YTQ': 'Tasiujaq',
 'YTR': 'Trenton',
 'YTS': 'Timmins',
 'YTZ': 'Toronto',
 'YUB': 'Tuktoyaktuk',
 'YUL': 'Montreal',
 'YUT': 'Repulse Bay',
 'YUX': 'Hall Beach',
 'YUY': 'Rouyn-Noranda',
 'YVB': 'Bonaventure',
 'YVC': 'La Ronge',
 'YVE': 'Vernon',
 'YVM': 'Qikiqtarjuaq',
 'YVO': "Val-d'Or",
 'YVP': 'Kuujjuaq',
 'YVQ': 'Norman Wells',
 'YVR': 'Vancouver',
 'YVT': 'Buffalo Narrows',
 'YVV': 'Wiarton',
 'YVZ': 'Deer Lake',
 'YWA': 'Petawawa',
 'YWG': 'Winnipeg',
 'YWJ': 'Deline',
 'YWK': 'Wabush',
 'YWL': 'Williams Lake',
 'YWP': 'Webequie',
 'YWY': 'Wrigley',
 'YXC': 'Cranbrook',
 'YXD': 'Edmonton',
 'YXE': 'Saskatoon',
 'YXH': 'Medicine Hat',
 'YXJ': 'Fort St.John',
 'YXK': 'Rimouski',
 'YXL': 'Sioux Lookout',
 'YXN': 'Whale Cove',
 'YXP': 'Pangnirtung',
 'YXQ': 'Beaver Creek',
 'YXR': 'Earlton',
 'YXS': 'Prince George',
 'YXT': 'Terrace',
 'YXU': 'London',
 'YXX': 'Abbotsford',
 'YXY': 'Whitehorse',
 'YXZ': 'Wawa',
 'YYB': 'North Bay',
 'YYC': 'Calgary',
 'YYD': 'Smithers',
 'YYE': 'Fort Nelson',
 'YYF': 'Penticton',
 'YYG': 'Charlottetown',
 'YYH': 'Taloyoak',
 'YYJ': 'Victoria',
 'YYL': 'Lynn Lake',
 'YYN': 'Swift Current',
 'YYQ': 'Churchill',
 'YYR': 'Goose Bay',
 'YYT': "St. John's",
 'YYU': 'Kapuskasing',
 'YYW': 'Armstrong',
 'YYY': 'Mont-Joli',
 'YYZ': 'Toronto',
 'YZD': 'Toronto',
 'YZE': 'Gore Bay',
 'YZF': 'Yellowknife',
 'YZG': 'Salluit',
 'YZH': 'Slave Lake',
 'YZP': 'Sandspit',
 'YZR': 'Sarnia',
 'YZS': 'Coral Harbour',
 'YZT': 'Port Hardy',
 'YZU': 'Whitecourt',
 'YZV': 'Sept-Iles',
 'YZW': 'Teslin',
 'YZX': 'Greenwood',
 'YZY': 'Mackenzie',
 'ZAC': 'York Landing',
 'YSN': 'Salmon Arm',
 'YDT': 'Burlington',
 'ZBD': 'Boundary Bay',
 'ILF': 'Ilford',
 'ZBF': 'Bathurst',
 'ZBM': 'Bromont',
 'ZEE': 'Kelsey',
 'ZEM': 'Eastmain River',
 'ZFA': 'Faro',
 'ZFD': 'Fond-Du-Lac',
 'ZFG': 'Pukatawagan',
 'ZFM': 'Fort Mcpherson',
 'ZFN': 'Tulita',
 'ZGF': 'Grand Forks',
 'ZGI': 'Gods River',
 'ZGR': 'Little Grand Rapids',
 'ZJG': 'Jenpeg',
 'ZJN': 'Swan River',
 'ZKE': 'Kashechewan',
 'YTD': 'Thicket Portage',
 'MSA': 'Muskrat Dam',
 'ZMH': '108 Mile',
 'PIW': 'Pikwitonei',
 'ZMT': 'Masset',
 'ZNG': 'Poplar River',
 'ZPB': 'Sachigo Lake',
 'ZPO': 'Pinehouse Lake',
 'ZRJ': 'Round Lake',
 'ZSJ': 'Sandy Lake',
 'ZSN': 'South Indian Lake',
 'ZST': 'Stewart',
 'ZTM': 'Shamattawa',
 'ZUC': 'Ignace',
 'ZUM': 'Churchill Falls',
 'ZWH': 'Lac Brochet',
 'ZWL': 'Wollaston Lake',
 'QLD': '',
 'BUJ': '',
 'BJA': 'Bejaia',
 'ALG': 'Algiers',
 'DJG': 'Djanet',
 'QFD': '',
 'VVZ': 'Illizi',
 'QSF': 'Setif',
 'TMR': 'Tamanrasset',
 'GJL': 'Jijel',
 'MZW': 'Mecheria',
 'QZN': '',
 'AAE': 'Annabah',
 'CZL': 'Constantine',
 'TEE': 'Tebessi',
 'BLJ': 'Batna',
 'HRM': '',
 'QDJ': '',
 'TID': 'Tiaret',
 'TIN': 'Tindouf',
 'QAS': '',
 'TAF': '',
 'TLM': 'Tlemcen',
 'ORN': 'Oran',
 'CBH': 'Bechar',
 'BFW': '',
 'MUW': '',
 'EBH': 'El Bayadh',
 'INF': 'In Guezzam',
 'BMW': 'Bordj Badji Mokhtar',
 'AZR': '',
 'BSK': 'Biskra',
 'ELG': '',
 'GHA': 'Ghardaia',
 'HME': 'Hassi Messaoud',
 'INZ': 'In Salah',
 'TGR': 'Touggourt',
 'LOO': 'Laghouat',
 'ELU': 'Guemar',
 'TMX': 'Timimoun',
 'OGX': 'Ouargla',
 'IAM': 'Amenas',
 'COO': 'Cotonou',
 'DJA': 'Djougou',
 'KDC': 'Kandi',
 'NAE': 'Natitingou',
 'PKO': 'Parakou',
 'SVF': 'Save',
 'XKY': 'Kaya',
 'OUG': 'Ouahigouya',
 'XDJ': 'Djibo',
 'XLU': 'Leo',
 'PUP': 'Po',
 'XBO': 'Boulsa',
 'XBG': 'Bogande',
 'DIP': 'Diapaga',
 'DOR': 'Dori',
 'FNG': "Fada N'gourma",
 'XGG': 'Gorom-Gorom',
 'XKA': 'Kantchari',
 'TMQ': 'Tambao',
 'XPA': 'Pama',
 'ARL': 'Arly',
 'XSE': 'Sebba',
 'TEG': 'Tenkodogo',
 'XZA': 'Zabre',
 'OUA': 'Ouagadougou',
 'BNR': 'Banfora',
 'DGU': 'Dedougou',
 'XGA': 'Gaoua',
 'XNU': 'Nouna',
 'BOY': 'Bobo Dioulasso',
 'TUQ': 'Tougan',
 'XDE': 'Diebougou',
 'XAR': 'Aribinda',
 'ACC': 'Accra',
 'TML': 'Tamale',
 'KMS': 'Kumasi',
 'NYI': 'Sunyani',
 'TKD': 'Sekondi-Takoradi',
 'ABJ': 'Abidjan',
 'OGO': 'Abengourou',
 'BXI': 'Boundiali',
 'BYK': '',
 'BQO': 'Bouna',
 'BDK': 'Bondoukou',
 'DIM': 'Dimbokro',
 'DJO': '',
 'FEK': 'Ferkessedougou',
 'GGN': 'Gagnoa',
 'GGO': 'Guiglo',
 'BBV': 'Grand-Bereby',
 'HGO': '',
 'MJC': '',
 'KEO': 'Odienne',
 'OFI': 'Ouango Fitini',
 'SEO': 'Seguela',
 'SPY': '',
 'ZSS': 'Sassandra',
 'TXU': 'Tabou',
 'ASK': 'Yamoussoukro',
 'ABV': 'Abuja',
 'AKR': 'Akure',
 'ABB': 'Asaba',
 'BNI': 'Benin',
 'CBQ': 'Calabar',
 'ENU': 'Enegu',
 'GMO': 'Gombe',
 'QUS': 'Gusau',
 'IBA': 'Ibadan',
 'ILR': 'Ilorin',
 'QOW': 'Owerri',
 'JOS': 'Jos',
 'KAD': 'Kaduna',
 'KAN': 'Kano',
 'MIU': 'Maiduguri',
 'MDI': 'Makurdi',
 'LOS': 'Lagos',
 'MXJ': 'Minna',
 'PHC': 'Port Harcourt',
 'SKO': 'Sokoto',
 'NBE': 'Enfidha',
 'YOL': 'Yola',
 'ZAR': 'Zaria',
 'MFQ': 'Maradi',
 'NIM': 'Niamey',
 'THZ': 'Tahoua',
 'AJY': 'Agadez',
 'ZND': 'Zinder',
 'TBJ': 'Tabarka',
 'MIR': 'Monastir',
 'TUN': 'Tunis',
 'OIZ': 'Sidi Ahmed',
 'GAF': 'Gafsa',
 'GAE': 'Gabes',
 'DJE': 'Djerba',
 'EBM': 'El Borma',
 'SFA': 'Sfax',
 'TOE': 'Tozeur',
 'LRL': 'Niamtougou',
 'LFW': 'Lome',
 'ANR': 'Antwerp',
 'BRU': 'Brussels',
 'CRL': 'Brussels',
 'KJK': 'Wevelgem',
 'LGG': 'Liege',
 'QNM': 'Namur',
 'OST': 'Ostend',
 'QHA': 'Hasselt',
 'OBL': 'Zoersel',
 'AOC': 'Altenburg',
 'HDF': 'Heringsdorf',
 'REB': 'Larz',
 'SXF': 'Berlin',
 'CSO': 'Magdeburg',
 'BBH': '',
 'ZMG': 'Magdeburg',
 'CBU': 'Cottbus',
 'GTI': 'Rugen',
 'PEF': 'Peenemunde',
 'DRS': 'Dresden',
 'ERF': 'Erfurt',
 'FRA': 'Frankfurt-am-Main',
 'FMO': 'Munster',
 'HAM': 'Hamburg',
 'THF': 'Berlin',
 'CGN': 'Cologne',
 'DUS': 'Dusseldorf',
 'MUC': 'Munich',
 'NUE': 'Nuremberg',
 'LEJ': 'Leipzig',
 'SCN': 'Saarbrucken',
 'STR': 'Stuttgart',
 'TXL': 'Berlin',
 'HAJ': 'Hannover',
 'BRE': 'Bremen',
 'QEF': 'Egelsbach',
 'HHN': 'Hahn',
 'MHG': 'Mannheim',
 'QMZ': 'Mainz',
 'SGE': '',
 'XFW': 'Hamburg',
 'KEL': 'Kiel',
 'LBC': 'Lubeck',
 'EUM': 'Neumunster',
 'FMM': 'Memmingen',
 'AAH': 'Aachen',
 'BNJ': 'Bonn',
 'ESS': '',
 'BFE': 'Bielefeld',
 'ZOJ': 'Marl',
 'MGL': 'Monchengladbach',
 'PAD': 'Paderborn',
 'NRN': 'Weeze',
 'DTM': 'Dortmund',
 'AGB': 'Augsburg',
 'OBF': '',
 'RBM': 'Straubing',
 'FDH': 'Friedrichshafen',
 'FRF': 'Oschersleben',
 'SZW': '',
 'BYU': 'Bayreuth',
 'QOB': 'Ansbach',
 'HOQ': 'Hof',
 'BBJ': 'Bitburg',
 'ZQW': 'Zweibrucken',
 'FKB': 'Baden-Baden',
 'ZQL': 'Donaueschingen',
 'LHA': '',
 'BWE': '',
 'KSF': 'Kassel',
 'BRV': 'Bremerhaven',
 'XLW': 'Lemwerder',
 'EME': 'Emden',
 'AGE': 'Wangerooge',
 'WVN': 'Wilhelmshaven',
 'JUI': 'Juist',
 'LGO': 'Langeoog',
 'ZOW': 'Klausheide',
 'BMK': 'Borkum',
 'NOD': 'Norddeich',
 'VAC': 'Cloppenburg',
 'NRD': 'Norderney',
 'BMR': 'Baltrum',
 'HEI': 'Busum',
 'FLF': 'Flensburg',
 'HGL': 'Helgoland',
 'PSH': 'Sankt Peter-Ording',
 'GWT': 'Westerland',
 'OHR': 'Wyk auf Fohr',
 'KDL': 'Kardla',
 'URE': 'Kuressaare',
 'EPU': 'Parnu',
 'TLL': 'Tallinn',
 'TAY': 'Tartu',
 'ENF': 'Enontekio',
 'QVE': 'Forssa',
 'KEV': 'Halli / Kuorevesi',
 'HEM': 'Helsinki',
 'HEL': 'Helsinki',
 'HYV': '',
 'KTQ': '',
 'IVL': 'Ivalo',
 'JOE': 'Joensuu / Liperi',
 'JYV': 'Jyvaskylan Maalaiskunta',
 'KAU': 'Kauhava',
 'KEM': 'Kemi / Tornio',
 'KAJ': 'Kajaani',
 'KHJ': '',
 'KOK': 'Kokkola / Kruunupyy',
 'KAO': 'Kuusamo',
 'KTT': 'Kittila',
 'KUO': 'Kuopio / Siilinjarvi',
 'QLF': '',
 'LPP': 'Lappeenranta',
 'MHQ': '',
 'MIK': 'Mikkeli',
 'OUL': 'Oulu / Oulunsalo',
 'POR': 'Pori',
 'RVN': 'Rovaniemi',
 'SVL': 'Savonlinna',
 'SJY': 'Seinajoki / Ilmajoki',
 'SOT': 'Sodankyla',
 'TMP': 'Tampere / Pirkkala',
 'TKU': 'Turku',
 'UTI': 'Utti / Valkeala',
 'VAA': 'Vaasa',
 'VRK': 'Varkaus / Joroinen',
 'YLI': '',
 'BFS': 'Belfast',
 'ENK': 'Enniskillen',
 'BHD': 'Belfast',
 'LDY': 'Derry',
 'BHX': 'Birmingham',
 'CVT': 'Coventry',
 'GLO': 'Staverton',
 'ORM': 'Northampton',
 'NQT': 'Nottingham',
 'MAN': 'Manchester',
 'DSA': 'Doncaster',
 'UPV': 'Upavon',
 'LYE': 'Lyneham',
 'DGX': 'St. Athan',
 'YEO': 'Yeovil',
 'CAL': 'Campbeltown',
 'EOI': 'Eday',
 'FIE': 'Fair Isle',
 'WHS': 'Whalsay',
 'COL': 'Coll Island',
 'NRL': 'North Ronaldsay',
 'OBN': 'North Connel',
 'PPW': 'Papa Westray',
 'SOY': 'Stronsay',
 'NDY': 'Sanday',
 'LWK': 'Lerwick',
 'WRY': 'Westray',
 'CSA': 'Colonsay',
 'HAW': 'Haverfordwest',
 'CWL': 'Cardiff',
 'SWS': 'Swansea',
 'BRS': 'Bristol',
 'LPL': 'Liverpool',
 'LTN': 'London',
 'LEQ': "Land's End",
 'PLH': 'Plymouth',
 'ISC': "St. Mary's",
 'BOH': 'Bournemouth',
 'SOU': 'Southampton',
 'BBP': 'Bembridge',
 'QLA': 'Lasham',
 'NQY': 'Newquay',
 'QUG': 'Chichester',
 'ACI': 'Saint Anne',
 'GCI': 'Saint Peter Port',
 'JER': 'Saint Helier',
 'ESH': 'Brighton',
 'BQH': 'London',
 'LGW': 'London',
 'KRH': 'Redhill',
 'LCY': 'London',
 'FAB': 'Farnborough',
 'BBS': 'Yateley',
 'LHR': 'London',
 'SEN': 'Southend',
 'LYX': 'Lydd',
 'MSE': 'Manston',
 'CAX': 'Carlisle',
 'BLK': 'Blackpool',
 'HUY': 'Grimsby',
 'BWF': 'Barrow-in-Furness',
 'LBA': 'Leeds',
 'CEG': 'Hawarden',
 'IOM': 'Castletown',
 'NCL': 'Newcastle',
 'MME': 'Durham',
 'EMA': 'Nottingham',
 'HLY': 'Angelsey',
 'KOI': 'Orkney Islands',
 'LSI': 'Lerwick',
 'WIC': 'Wick',
 'ABZ': 'Aberdeen',
 'INV': 'Inverness',
 'GLA': 'Glasgow',
 'EDI': 'Edinburgh',
 'ILY': 'Port Ellen',
 'PIK': 'Glasgow',
 'BEB': 'Balivanich',
 'SCS': 'Shetland Islands',
 'DND': 'Dundee',
 'SYY': 'Stornoway',
 'BRR': 'Eoligarry',
 'PSL': 'Perth',
 'TRE': 'Balemartine',
 'UNT': 'Shetland Islands',
 'BOL': 'Ballykelly',
 'FSS': 'Kinloss',
 'ADX': 'St. Andrews',
 'LMO': 'Lossiemouth',
 'CBG': 'Cambridge',
 'NWI': 'Norwich',
 'STN': 'London',
 'QFO': 'Duxford',
 'HYC': 'High Wycombe',
 'EXT': 'Exeter',
 'FZO': 'Bristol',
 'OXF': 'Kidlington',
 'RCS': 'Rochester',
 'BEX': 'Benson',
 'LKZ': 'Lakenheath',
 'MHZ': 'Mildenhall',
 'QUY': 'St. Ives',
 'FFD': 'Fairford',
 'BZZ': 'Brize Norton',
 'ODH': 'Odiham',
 'WXF': 'Wethersfield',
 'NHT': 'London',
 'QCY': 'Coningsby',
 'BEQ': 'Thetford',
 'OKH': 'Cottesmore',
 'SQZ': 'Scampton',
 'HRT': 'Linton-On-Ouse',
 'WTN': 'Waddington',
 'MRH': 'Marham',
 'MPN': 'Mount Pleasant',
 'AMS': 'Amsterdam',
 'MST': 'Maastricht',
 'QAR': 'Arnhem',
 'EIN': 'Eindhoven',
 'GRQ': 'Groningen',
 'GLZ': 'Breda',
 'DHR': 'Den Helder',
 'LEY': 'Lelystad',
 'LWR': 'Leeuwarden',
 '---': '',
 'RTM': 'Rotterdam',
 'ENS': 'Enschede',
 'UDE': 'Uden',
 'WOE': 'Bergen Op Zoom',
 'BYT': 'Bantry',
 'BLY': 'Belmullet',
 'NNR': 'Inverin',
 'CLB': 'Castlebar',
 'WEX': 'Wexford',
 'ORK': 'Cork',
 'GWY': 'Galway',
 'CFN': 'Donegal',
 'DUB': 'Dublin',
 'IOR': 'Inis Mor',
 'INQ': 'Inis Oirr',
 'KKY': 'Kilkenny',
 'NOC': 'Charleston',
 'KIR': 'Killarney',
 'LTR': 'Letterkenny',
 'IIA': 'Inis Meain',
 'SNN': 'Shannon',
 'SXL': 'Sligo',
 'WAT': 'Waterford',
 '0': 'Tesouro',
 'AAR': 'Aarhus',
 'BLL': 'Billund',
 'CPH': 'Copenhagen',
 'EBJ': 'Esbjerg',

Una vez que ya lo tengo me hago un df llamado bookings con las columnas que me interesan asio tarda menos en ejecutarse las cosas

In [26]:
book.head()

,act_date,source,pos_ctry,pos_iata,pos_oid,rloc,cre_date,duration,distance,dep_port,...,carrier,bkg_class,cab_class,brd_time,off_time,pax,year,month,oid,iata
0,2013-03-05 00:00:00,1A,DE,a68dd7ae953c8acfb187a1af2dcbe123,1a11ae49fcbf545fd2afc1a24d88d2b7,ea65900e72d71f4626378e2ebd298267,2013-02-22 00:00:00,1708,0,ZRH,...,VI,T,Y,2013-03-07 08:50:00,2013-03-07 11:33:37,-1.0,2013.0,3.0,NULL,LHR
1,2013-03-26 00:00:00,1A,US,e612b9eeeee6f17f42d9b0d3b79e75ca,7437560d8f276d6d05eeb806d9e7edee,737295a86982c941f1c2da9a46a14043,2013-03-26 00:00:00,135270,0,SAL,...,NV,L,Y,2013-04-12 13:04:00,2013-04-12 22:05:40,1.0,2013.0,3.0,NULL,CLT
2,2013-03-26 00:00:00,1A,US,e612b9eeeee6f17f42d9b0d3b79e75ca,7437560d8f276d6d05eeb806d9e7edee,737295a86982c941f1c2da9a46a14043,2013-03-26 00:00:00,135270,0,SAL,...,NV,U,Y,2013-07-15 07:00:00,2013-07-15 11:34:51,1.0,2013.0,3.0,NULL,CLT
3,2013-03-26 00:00:00,1A,AU,0f984b3bb6bd06661c95529bbd6193bc,36472c6dbaf7afec9136ac40364e2794,5ecf00fdcbcec761c43dc7285253d0c1,2013-03-26 00:00:00,30885,0,AKL,...,XK,G,Y,2013-04-24 23:59:00,2013-04-25 16:06:31,1.0,2013.0,3.0,SYDA82546,SVO
4,2013-03-26 00:00:00,1A,AU,0f984b3bb6bd06661c95529bbd6193bc,36472c6dbaf7afec9136ac40364e2794,5ecf00fdcbcec761c43dc7285253d0c1,2013-03-26 00:00:00,30885,0,AKL,...,XK,G,Y,2013-05-14 20:15:00,2013-05-16 10:44:50,1.0,2013.0,3.0,SYDA82546,SVO

In [27]:
bookings = book[['iata', 'pax']]

In [29]:
bookings.head()

  iata  pax
0  LHR -1.0
1  CLT  1.0
2  CLT  1.0
3  SVO  1.0
4  SVO  1.0

inclumos una columna con la ciudad, haciendo mapping con el diccionario que hemos creado

In [30]:
bookings['city'] = bookings['iata'].map(dicc)

C:\Users\ORTEGA\Anaconda\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [32]:
bookings.head()

  iata  pax       city
0  LHR -1.0     London
1  CLT  1.0  Charlotte
2  CLT  1.0  Charlotte
3  SVO  1.0     Moscow
4  SVO  1.0     Moscow

creamos un groupby por aeropuerto sumando pax

In [34]:
by_arr = bookings.groupby('iata').sum()

Ahora lo agrupamos de mayor a menor

In [37]:
by_arr = by_arr.sort_values(by = 'pax',ascending = False)

In [39]:
by_arr

          pax
iata
LHR   88809.0
MCO   70930.0
LAX   70530.0
LAS   69630.0
JFK   66270.0
...       ...
MYJ     -80.0
UPG     -90.0
XWG     -90.0
MZV    -350.0
AYQ   -1270.0

[2275 rows x 1 columns]

Realizamos un reset index para hacer el maping de nuevo con la ciudad

In [40]:
by_arr_city = by_arr.reset_index()

In [42]:
by_arr_city['city'] = by_arr_city['iata'].map(dicc)

Ponemos el indice de nuevo

In [46]:
by_arr_city.set_index('iata', inplace=True)

Simplemente ponemos el top 10 y listo

In [47]:
by_arr_city.head(10)

          pax           city
iata
LHR   88809.0         London
MCO   70930.0        Orlando
LAX   70530.0    Los Angeles
LAS   69630.0      Las Vegas
JFK   66270.0       New York
CDG   64490.0          Paris
BKK   59460.0        Bangkok
MIA   58150.0          Miami
SFO   58000.0  San Francisco
DXB   55590.0          Dubai

# EXERCISE 1

In [7]:
book.index

RangeIndex(start=0, stop=10000010, step=1)

# EXERCISE 2


Top 10 arrival airports in the world in 2013 (using the bookings file)

In [8]:
book['act_date           ']

0           2013-03-05 00:00:00
1           2013-03-26 00:00:00
2           2013-03-26 00:00:00
3           2013-03-26 00:00:00
4           2013-03-26 00:00:00
                   ...
10000005    2013-05-18 00:00:00
10000006    2013-05-18 00:00:00
10000007    2013-05-28 00:00:00
10000008    2013-05-28 00:00:00
10000009    2013-05-28 00:00:00
Name: act_date           , Length: 10000010, dtype: object

In [9]:
top_arr = book['arr_port'].value_counts().head(10)

In [10]:
top_arr

LHR         215551
JFK         158930
CDG         149390
LAX         143220
DXB         135640
BKK         130420
MIA         117820
SFO         110970
MNL         109530
ORD          99750
Name: arr_port, dtype: int64

In [48]:
book['pax']

0          -1.0
1           1.0
2           1.0
3           1.0
4           1.0
           ...
10000005   -1.0
10000006    1.0
10000007    1.0
10000008    1.0
10000009    1.0
Name: pax, Length: 10000010, dtype: float64

In [49]:
book['pax'].value_counts()

 1.0     5032696
-1.0     2203551
 2.0     1185822
-2.0      630010
 3.0      262770
          ...
 64.0         10
-76.0         10
 66.0         10
-90.0         10
 51.0         10
Name: pax, Length: 124, dtype: int64

In [12]:
book['off_port'][5]

'LGA     '

In [ ]:
by_arr = book.groupby('iata').sum()["pax"]

Print the top 10 arrival airports in the standard output, including the number of
passengers.

In [16]:
by_arr.head(3)

arr_port
AAB          30.0
AAE         810.0
AAL         810.0
Name: pax, dtype: float64

In [18]:
type(by_arr)

pandas.core.series.Series

In [33]:
by_air_city = by_arr.reset_index()

In [34]:
type(by_air_city)

pandas.core.frame.DataFrame

In [35]:
by_air_city["city"] = by_air_city["arr_port"].index.map(dicc)

In [37]:
by_air_city.head(5)

   arr_port     pax  city
0  AAB         30.0   NaN
1  AAE        810.0   NaN
2  AAL        810.0   NaN
3  AAN         20.0   NaN
4  AAQ       1650.0   NaN

In [15]:
by_arr.sort_values(ascending = False).head(10)

arr_port
LHR         88809.0
MCO         70930.0
LAX         70530.0
LAS         69630.0
JFK         66270.0
CDG         64490.0
BKK         59460.0
MIA         58150.0
SFO         58000.0
DXB         55590.0
Name: pax, dtype: float64

In [22]:
datas = pd.read_json('https://raw.githubusercontent.com/mwgg/Airports/master/airports.json') 
datas

,00AK,00AL,00AZ,00CA,00CO,00FA,00FL,00GA,00ID,00IL,...,ZYMD,ZYMH,ZYQQ,ZYTH,ZYTL,ZYTN,ZYTX,ZYXC,ZYYJ,ZYYY
icao,00AK,00AL,00AZ,00CA,00CO,00FA,00FL,00GA,00ID,00IL,...,ZYMD,ZYMH,ZYQQ,ZYTH,ZYTL,ZYTN,ZYTX,ZYXC,ZYYJ,ZYYY
iata,,,,,,,,,,,...,MDG,OHE,NDG,,DLC,TNH,SHE,XEN,YNJ,
name,Lowell Field,Epps Airpark,Cordes Airport,Goldstone /Gts/ Airport,Cass Field,Grass Patch Airport,River Oak Airport,Lt World Airport,Delta Shores Airport,Hammer Airport,...,Mudanjiang Hailang International Airport,Gu-Lian Airport,Qiqihar Sanjiazi Airport,Tahe Airport,Zhoushuizi Airport,Tonghua Sanyuanpu Airport,Taoxian Airport,Xingcheng Air Base,Yanji Chaoyangchuan Airport,Shenyang Dongta Airport
city,Anchor Point,Harvest,Cordes,Barstow,Briggsdale,Bushnell,Okeechobee,Lithonia,Clark Fork,Polo,...,Mudanjiang,Mohe,Qiqihar,Tahe,Dalian,Tonghua,Shenyang,,Yanji,Shenyang
state,Alaska,Alabama,Arizona,California,Colorado,Florida,Florida,Georgia,Idaho,Illinois,...,Heilongjiang,Heilongjiang,Heilongjiang,Heilongjiang,Liaoning,Jilin,Liaoning,Liaoning,Jilin,Liaoning
country,US,US,US,US,US,US,US,US,US,US,...,CN,CN,CN,CN,CN,CN,CN,CN,CN,CN
elevation,450,820,3810,3038,4830,53,35,700,2064,840,...,883,1836,477,1240,107,1200,198,30,624,0
lat,59.9492,34.8648,34.3056,35.3505,40.6222,28.6455,27.2309,33.7675,48.1453,41.9784,...,44.5241,52.9128,47.2396,52.2244,38.9657,42.2539,41.6398,40.5803,42.8828,41.7844
lon,-151.696,-86.7703,-112.165,-116.888,-104.344,-82.219,-80.9692,-84.0683,-116.214,-89.5604,...,129.569,122.43,123.918,124.72,121.539,125.703,123.483,120.698,129.451,123.496
tz,America/Anchorage,America/Chicago,America/Phoenix,America/Los_Angeles,America/Denver,America/New_York,America/New_York,America/New_York,America/Los_Angeles,America/Chicago,...,Asia/Shanghai,Asia/Shanghai,Asia/Shanghai,Asia/Shanghai,Asia/Shanghai,Asia/Shanghai,Asia/Shanghai,Asia/Shanghai,Asia/Shanghai,Asia/Shanghai

In [23]:
datas = datas.T

In [24]:
datas.head(5)

,icao,iata,name,city,state,country,elevation,lat,lon,tz
00AK,00AK,,Lowell Field,Anchor Point,Alaska,US,450,59.9492,-151.696,America/Anchorage
00AL,00AL,,Epps Airpark,Harvest,Alabama,US,820,34.8648,-86.7703,America/Chicago
00AZ,00AZ,,Cordes Airport,Cordes,Arizona,US,3810,34.3056,-112.165,America/Phoenix
00CA,00CA,,Goldstone /Gts/ Airport,Barstow,California,US,3038,35.3505,-116.888,America/Los_Angeles
00CO,00CO,,Cass Field,Briggsdale,Colorado,US,4830,40.6222,-104.344,America/Denver

In [25]:
datas[datas['city'] == 'Miami']

,icao,iata,name,city,state,country,elevation,lat,lon,tz
14FA,14FA,,Burrs Strip,Miami,Florida,US,10,25.5701,-80.3998,America/New_York
5TE8,5TE8,,Willis N Clark Airport,Miami,Texas,US,3086,35.7612,-100.752,America/Chicago
70OK,70OK,,Old 66 Strip,Miami,Oklahoma,US,853,36.8337,-94.9041,America/Chicago
FA35,FA35,,Lindbergh's Landing Airport,Miami,Florida,US,9,25.6195,-80.4887,America/New_York
FL31,FL31,,Mjd STOLport,Miami,Florida,US,6,25.5546,-80.5539,America/New_York
K3E0,K3E0,,Miami Roberts County Airport,Miami,Texas,US,2720,35.7139,-100.603,America/Chicago
KMIA,KMIA,MIA,Miami International Airport,Miami,Florida,US,8,25.7932,-80.2906,America/New_York
KMIO,KMIO,,Miami Municipal Airport,Miami,Oklahoma,US,808,36.9092,-94.8875,America/Chicago
KOPF,KOPF,,Opa-locka Executive Airport,Miami,Florida,US,8,25.907,-80.2784,America/New_York
KTMB,KTMB,TMB,Miami Executive Airport,Miami,Miami,US,10,25.6476,-80.4332,America/New_York
KTNT,KTNT,,Dade Collier Training and Transition Airport,Miami,Florida,US,13,25.8618,-80.897,America/New_York

In [26]:
type(datas['iata'][0])

str

De esta tabla voy a sacar un diccionario para luego mapear con el codigo iata y la ciudad

In [27]:
dicc = pd.Series(datas.city.values,index=datas.iata).to_dict()

In [28]:
dicc

{'': 'Shenyang',
 'ICY': 'Icy Bay',
 'HGZ': 'Hogatza',
 'BYW': 'Blakely Island',
 'BDF': 'Bradford',
 'BCS': 'Belle Chasse',
 'BWL': 'Blackwell',
 'DUF': 'Corolla',
 'FOB': 'Fort Bragg',
 'ALX': 'Alexander City',
 'AFT': 'Bila',
 'RNA': 'Arona',
 'ATD': 'Atoifi',
 'VEV': 'Barakoma',
 'BPF': 'Batuna Mission Station',
 'GEF': 'Liangia',
 'AKS': 'Auki',
 'BNY': 'Anua',
 'CHY': '',
 'BAS': 'Ballalae',
 'FRE': 'Fera Island',
 'HIR': 'Honiara',
 'MBU': 'Mbambanakira',
 'AVU': '',
 'IRA': 'Kirakira',
 'SCZ': 'Santa Cruz/Graciosa Bay/Luova',
 'MUA': '',
 'GZO': 'Gizo',
 'MNY': 'Stirling Island',
 'PRS': 'Parasi',
 'RNL': 'Rennell Island',
 'EGM': 'Sege',
 'NNB': 'Santa Ana Island',
 'RUS': 'Marau',
 'VAO': 'Suavanao',
 'XYA': 'Yandina',
 'KGE': 'Kagau Island',
 'KWS': 'Kwailabesi',
 'GTA': 'Gatokae',
 'RIN': 'Ringi Cove',
 'RBV': 'Ramata',
 'CEX': 'Chena Hot Springs',
 'HED': 'Herendeen Bay',
 'TWE': 'Taylor',
 'CDL': 'Candle',
 'BSZ': 'Egegik',
 'BSW': 'Boswell Bay',
 'INU': 'Yaren District',
 'ATP': 'Aitape',
 'AMU': 'Amanab',
 'ADC': 'Andekombe',
 'AIE': 'Aiome',
 'KPM': '',
 'AUJ': 'Ambunti',
 'AWB': 'Awaba',
 'AYU': 'Aiyura Valley',
 'VMU': 'Baimuru',
 'BDZ': '',
 'BUA': 'Buka Island',
 'OPU': 'Balimo',
 'BUL': 'Bulolo',
 'CMU': 'Kundiawa',
 'DER': 'Derim',
 'DAU': 'Daru',
 'XYR': 'Yellow River Mission',
 'FNE': 'Fane Mission',
 'FIN': 'Buki',
 'FAQ': 'Frieda River',
 'GKA': 'Goronka',
 'GRL': 'Au',
 'GAR': 'Garaina',
 'GUR': 'Gurney',
 'GAP': 'Gusap',
 'PNP': 'Popondetta',
 'GMI': 'Gasmata Island',
 'GVI': 'Green River',
 'HKN': 'Hoskins',
 'KIE': 'Kieta',
 'LSA': 'Losuia',
 'KBM': '',
 'KDR': 'Kandrian',
 'UNG': 'Kiunga',
 'KRI': 'Kikori',
 'KMA': 'Kerema',
 'KKD': 'Kokoda',
 'KZF': 'Kaintiba',
 'KUQ': 'Kuri',
 'KVG': 'Kavieng',
 'KWO': 'Kawito',
 'LNV': 'Londolovit',
 'LMY': 'Lake Murray',
 'LMI': 'Lumi',
 'MYX': 'Menyamya',
 'MAG': 'Madang',
 'HGU': 'Mount Hagen',
 'MXK': 'Mindik',
 'GUV': 'Mougulu',
 'MDU': '',
 'MAS': '',
 'MXH': 'Moro',
 'MIS': 'Misima Island',
 'GBF': 'Negarbo',
 'MFO': 'Manguna',
 'UKU': 'Nuku',
 'LAE': 'Nadzab',
 'OGE': '',
 'OSE': 'Omora',
 'PDI': 'Pindiu',
 'POM': 'Port Moresby',
 'KRJ': '',
 'RMN': '',
 'KMR': 'Karimui',
 'SBE': '',
 'NIS': 'Simberi Island',
 'SIL': 'Sila Mission',
 'SIM': 'Simbai',
 'SKC': 'Suki',
 'TIZ': 'Tari',
 'TBG': 'Tabubil',
 'TFM': 'Telefomin',
 'TPI': 'Tapini',
 'TAJ': 'Aitape',
 'RAB': 'Tokua',
 'TKW': 'Tekin',
 'TFI': 'Tufi',
 'VAI': '',
 'WAO': 'Wabo',
 'WBM': '',
 'AGL': '',
 'WWK': 'Wewak',
 'WOA': 'Wonenara',
 'WSU': 'Wasu',
 'WTP': 'Fatima Mission',
 'WUG': 'Wau',
 'JEG': 'Aasiaat',
 'UAK': 'Narsarsuaq',
 'CNP': 'Neerlerit Inaat',
 'GOH': 'Nuuk',
 'JAV': 'Ilulissat',
 'KUS': 'Kulusuk',
 'JSU': 'Maniitsoq',
 'JFR': 'Paamiut',
 'NAQ': 'Qaanaaq',
 'SFJ': 'Kangerlussuaq',
 'JHS': 'Sisimiut',
 'THU': 'Thule',
 'JUV': 'Upernavik',
 'JQA': 'Uummannaq',
 'AEY': 'Akureyri',
 'BIU': 'Bildudalur',
 'BGJ': 'Borgarfjordur eystri',
 'BJD': 'Bakkafjordur',
 'BLO': 'Blonduos',
 'BQD': 'Budardalur',
 'BXV': 'Breiddalsvik',
 'DJU': 'Djupivogur',
 'EGS': 'Egilsstadir',
 'FAS': 'Faskrudsfjordur',
 'FAG': 'Fagurholsmyri',
 'GUU': 'Grundarfjordur',
 'GJR': 'Gjogur',
 'GRY': 'Grimsey',
 'HVK': 'Holmavik',
 'HFN': 'Hornafjordur',
 'FLI': 'Flateyri',
 'HZK': 'Husavik',
 'HVM': 'Hvammstangi',
 'HLO': 'Onundarfjordur',
 'IFJ': 'Isafjordur',
 'KEF': 'Reykjavik',
 'OPA': 'Kopasker',
 'SAK': 'Saudarkrokur',
 'NOR': 'Nordfjordur',
 'OFJ': 'Olafsfjordur',
 'PFJ': 'Patreksfjordur',
 'RHA': 'Reykholar',
 'OLI': 'Rif',
 'RFN': 'Raufarhofn',
 'RKV': 'Reykjavik',
 'MVA': 'Myvatn',
 'SIJ': 'Siglufjordur',
 'SYK': 'Stykkisholmur',
 'TEY': 'Tingeyri',
 'THO': 'Thorshofn',
 'VEY': 'Vestmannaeyjar',
 'VPN': 'Vopnafjordur',
 'PRN': 'Prishtina',
 'YZZ': 'Trail',
 'YAA': 'Anahim Lake',
 'DGF': 'Douglas Lake',
 'JHL': 'Albian Village',
 'DUQ': 'Duncan',
 'YWM': 'Williams Harbour',
 'YFX': 'St. Lewis',
 'YHA': 'Port Hope Simpson',
 'YRG': 'Rigolet',
 'DVK': 'Diavik',
 'YCK': 'Colville Lake',
 'YLE': 'Whati',
 'NML': 'Fort McMurray',
 'ZSP': 'St. Paul',
 'DAS': 'Great Bear Lake',
 'YFI': 'Suncor Energy Site',
 'SUR': 'Summer Beaver',
 'YAX': 'Angling Lake',
 'WNN': 'Wunnumin Lake',
 'YNO': 'North Spirit Lake',
 'XBE': 'Bearskin Lake',
 'KIF': 'Kingfisher Lake',
 'YOG': 'Ogoki Post',
 'YEB': 'Bar River',
 'YHP': 'Poplar Hill',
 'YNX': 'Snap Lake',
 'YKU': 'Chisasibi',
 'ZTB': 'Tete-a-la-Baleine',
 'YAU': 'Kattiniq',
 'ZLT': 'La Tabatiere',
 'YAC': 'Cat Lake',
 'YAR': 'La Grande-3',
 'YAG': 'Fort Frances',
 'YAH': 'La Grande-4',
 'YAL': 'Alert Bay',
 'YAM': 'Sault Ste Marie',
 'XKS': 'Kasabonika',
 'YKG': 'Kangirsuk',
 'YAT': 'Attawapiskat',
 'YAW': 'Halifax',
 'YAY': 'St. Anthony',
 'YAZ': 'Tofino',
 'YBA': 'Banff',
 'YBB': 'Kugaaruk',
 'YBC': 'Baie-Comeau',
 'QBC': 'Bella Coola',
 'YBE': 'Uranium City',
 'YBY': 'Bonnyville',
 'YBG': 'Bagotville',
 'YBK': 'Baker Lake',
 'YBL': 'Campbell River',
 'XTL': 'Tadoule Lake',
 'YBR': 'Brandon',
 'YBT': 'Brochet',
 'YBV': 'Berens River',
 'YBX': 'Lourdes-De-Blanc-Sablon',
 'YRF': 'Cartwright',
 'YCB': 'Cambridge Bay',
 'YCC': 'Cornwall',
 'YCD': 'Nanaimo',
 'YCE': 'Centralia',
 'YCG': 'Castlegar',
 'YCH': 'Miramichi',
 'XCM': 'Chatham-Kent',
 'YCL': 'Charlo',
 'YCN': 'Cochrane',
 'YCO': 'Kugluktuk',
 'YCQ': 'Chetwynd',
 'YCR': 'Cross Lake',
 'YCS': 'Chesterfield Inlet',
 'YCY': 'Clyde River',
 'YCZ': 'Fairmont Hot Springs',
 'YDA': 'Dawson City',
 'YDB': 'Burwash',
 'YDF': 'Deer Lake',
 'YDM': 'Ross River',
 'YDN': 'Dauphin',
 'YDO': 'Dolbeau-St-Felicien',
 'YDP': 'Nain',
 'YDQ': 'Dawson Creek',
 'YEG': 'Edmonton',
 'YEK': 'Arviat',
 'YEL': 'Elliot Lake',
 'YEM': 'Manitowaning',
 'YEN': 'Estevan',
 'YER': 'Fort Severn',
 'YET': 'Edson',
 'YEU': 'Eureka',
 'YEV': 'Inuvik',
 'YEY': 'Amos',
 'YFA': 'Fort Albany',
 'YFB': 'Iqaluit',
 'YFC': 'Fredericton',
 'YFE': 'Forestville',
 'YFH': 'Fort Hope',
 'YTM': 'Riviere Rouge',
 'YFO': 'Flin Flon',
 'YFR': 'Fort Resolution',
 'YFS': 'Fort Simpson',
 'YMN': 'Makkovik',
 'YGB': 'Texada',
 'YGD': 'Goderich',
 'YGH': 'Fort Good Hope',
 'YGK': 'Kingston',
 'YGL': 'La Grande Riviere',
 'YGM': 'Gimli',
 'YGO': 'Gods Lake Narrows',
 'YGP': 'Gaspe',
 'YGQ': 'Geraldton',
 'YGR': 'Iles-de-la-Madeleine',
 'YGT': 'Igloolik',
 'YGV': 'Havre St-Pierre',
 'YGW': 'Kuujjuarapik',
 'YGX': 'Gillam',
 'YGZ': 'Grise Fiord',
 'YQC': 'Quaqtaq',
 'YHD': 'Dryden',
 'YHE': 'Hope',
 'YHF': 'Hearst',
 'YNS': 'Nemiscau',
 'YHI': 'Ulukhaktok',
 'YHK': 'Gjoa Haven',
 'YHM': 'Hamilton',
 'YHN': 'Hornepayne',
 'YHO': 'Hopedale',
 'YHR': 'Chevery',
 'YHT': 'Haines Junction',
 'YHU': 'Montreal',
 'YHY': 'Hay River',
 'YHZ': 'Halifax',
 'YIB': 'Atikokan',
 'YDG': 'Digby',
 'YIF': 'St-Augustin',
 'YIK': 'Ivujivik',
 'YIO': 'Pond Inlet',
 'YIV': 'Island Lake',
 'YJF': 'Fort Liard',
 'YJN': 'St Jean',
 'YJT': 'Stephenville',
 'YKA': 'Kamloops',
 'LAK': 'Aklavik',
 'YKF': 'Kitchener',
 'YKJ': 'Key Lake',
 'YKL': 'Schefferville',
 'AKV': 'Akulivik',
 'YKQ': 'Waskaganish',
 'YKX': 'Kirkland Lake',
 'YKY': 'Kindersley',
 'YKZ': 'Toronto',
 'YPJ': 'Aupaluk',
 'YLC': 'Kimmirut',
 'YLD': 'Chapleau',
 'YLH': 'Lansdowne House',
 'YLJ': 'Meadow Lake',
 'YSG': "Lutselk'e",
 'YLL': 'Lloydminster',
 'YLR': 'Leaf Rapids',
 'YLK': 'Barrie-Orillia',
 'YLT': 'Alert',
 'XGR': 'Kangiqsualujjuaq',
 'YLW': 'Kelowna',
 'YMA': 'Mayo',
 'YME': 'Matane',
 'YMG': 'Manitouwadge',
 'YMH': "Mary's Harbour",
 'YMJ': 'Moose Jaw',
 'YML': 'Charlevoix',
 'YMM': 'Fort McMurray',
 'YMO': 'Moosonee',
 'YMT': 'Chibougamau',
 'YUD': 'Umiujaq',
 'YMX': 'Montreal',
 'YNA': 'Natashquan',
 'YNC': 'Wemindji',
 'YND': 'Gatineau',
 'YNE': 'Norway House',
 'YNL': 'Points North Landing',
 'YNM': 'Matagami',
 'YNN': 'Nejanilini Lake',
 'HZP': 'Fort Mackay',
 'YOA': 'Ekati',
 'YOC': 'Old Crow',
 'YOD': 'Cold Lake',
 'YOH': 'Oxford House',
 'YOJ': 'High Level',
 'YOO': 'Oshawa',
 'YOP': 'Rainbow Lake',
 'YOS': 'Owen Sound',
 'YOW': 'Ottawa',
 'YPA': 'Prince Albert',
 'YPC': 'Paulatuk',
 'YPS': 'Port Hawkesbury',
 'YPE': 'Peace River',
 'YPG': 'Portage',
 'YPH': 'Inukjuak',
 'YPL': 'Pickle Lake',
 'YPM': 'Pikangikum',
 'YPN': 'Port-Menier',
 'YPO': 'Peawanuck',
 'YPQ': 'Peterborough',
 'YPR': 'Prince Rupert',
 'YPW': 'Powell River',
 'YPX': 'Puvirnituq',
 'YPY': 'Fort Chipewyan',
 'YQA': 'Muskoka',
 'YQB': 'Quebec',
 'YQD': 'The Pas',
 'YQF': 'Red Deer',
 'YQG': 'Windsor',
 'YQH': 'Watson Lake',
 'YQI': 'Yarmouth',
 'YQK': 'Kenora',
 'YQL': 'Lethbridge',
 'YQM': 'Moncton',
 'YQN': 'Nakina',
 'YQQ': 'Comox',
 'YQR': 'Regina',
 'YQS': 'St Thomas',
 'YQT': 'Thunder Bay',
 'YQU': 'Grande Prairie',
 'YQV': 'Yorkton',
 'YQW': 'North Battleford',
 'YQX': 'Gander',
 'YQY': 'Sydney',
 'YQZ': 'Quesnel',
 'YRA': 'Gameti',
 'YRB': 'Resolute Bay',
 'YRI': 'Riviere-du-Loup',
 'YRJ': 'Roberval',
 'YRL': 'Red Lake',
 'YRO': 'Ottawa',
 'YRP': 'Carp',
 'YRQ': 'Trois-Rivieres',
 'YRS': 'Red Sucker Lake',
 'YRT': 'Rankin Inlet',
 'YRV': 'Revelstoke',
 'YSB': 'Sudbury',
 'YSC': 'Sherbrooke',
 'YSF': 'Stony Rapids',
 'YSH': 'Smiths Falls',
 'YSJ': 'Saint John',
 'YSK': 'Sanikiluaq',
 'YSL': 'St Leonard',
 'YSM': 'Fort Smith',
 'YCM': 'St Catharines',
 'YSP': 'Marathon',
 'YST': 'St. Theresa Point',
 'YSU': 'Summerside',
 'YSY': 'Sachs Harbour',
 'YTA': 'Pembroke',
 'YTE': 'Cape Dorset',
 'YTF': 'Alma',
 'YTH': 'Thompson',
 'YTL': 'Big Trout Lake',
 'YTQ': 'Tasiujaq',
 'YTR': 'Trenton',
 'YTS': 'Timmins',
 'YTZ': 'Toronto',
 'YUB': 'Tuktoyaktuk',
 'YUL': 'Montreal',
 'YUT': 'Repulse Bay',
 'YUX': 'Hall Beach',
 'YUY': 'Rouyn-Noranda',
 'YVB': 'Bonaventure',
 'YVC': 'La Ronge',
 'YVE': 'Vernon',
 'YVM': 'Qikiqtarjuaq',
 'YVO': "Val-d'Or",
 'YVP': 'Kuujjuaq',
 'YVQ': 'Norman Wells',
 'YVR': 'Vancouver',
 'YVT': 'Buffalo Narrows',
 'YVV': 'Wiarton',
 'YVZ': 'Deer Lake',
 'YWA': 'Petawawa',
 'YWG': 'Winnipeg',
 'YWJ': 'Deline',
 'YWK': 'Wabush',
 'YWL': 'Williams Lake',
 'YWP': 'Webequie',
 'YWY': 'Wrigley',
 'YXC': 'Cranbrook',
 'YXD': 'Edmonton',
 'YXE': 'Saskatoon',
 'YXH': 'Medicine Hat',
 'YXJ': 'Fort St.John',
 'YXK': 'Rimouski',
 'YXL': 'Sioux Lookout',
 'YXN': 'Whale Cove',
 'YXP': 'Pangnirtung',
 'YXQ': 'Beaver Creek',
 'YXR': 'Earlton',
 'YXS': 'Prince George',
 'YXT': 'Terrace',
 'YXU': 'London',
 'YXX': 'Abbotsford',
 'YXY': 'Whitehorse',
 'YXZ': 'Wawa',
 'YYB': 'North Bay',
 'YYC': 'Calgary',
 'YYD': 'Smithers',
 'YYE': 'Fort Nelson',
 'YYF': 'Penticton',
 'YYG': 'Charlottetown',
 'YYH': 'Taloyoak',
 'YYJ': 'Victoria',
 'YYL': 'Lynn Lake',
 'YYN': 'Swift Current',
 'YYQ': 'Churchill',
 'YYR': 'Goose Bay',
 'YYT': "St. John's",
 'YYU': 'Kapuskasing',
 'YYW': 'Armstrong',
 'YYY': 'Mont-Joli',
 'YYZ': 'Toronto',
 'YZD': 'Toronto',
 'YZE': 'Gore Bay',
 'YZF': 'Yellowknife',
 'YZG': 'Salluit',
 'YZH': 'Slave Lake',
 'YZP': 'Sandspit',
 'YZR': 'Sarnia',
 'YZS': 'Coral Harbour',
 'YZT': 'Port Hardy',
 'YZU': 'Whitecourt',
 'YZV': 'Sept-Iles',
 'YZW': 'Teslin',
 'YZX': 'Greenwood',
 'YZY': 'Mackenzie',
 'ZAC': 'York Landing',
 'YSN': 'Salmon Arm',
 'YDT': 'Burlington',
 'ZBD': 'Boundary Bay',
 'ILF': 'Ilford',
 'ZBF': 'Bathurst',
 'ZBM': 'Bromont',
 'ZEE': 'Kelsey',
 'ZEM': 'Eastmain River',
 'ZFA': 'Faro',
 'ZFD': 'Fond-Du-Lac',
 'ZFG': 'Pukatawagan',
 'ZFM': 'Fort Mcpherson',
 'ZFN': 'Tulita',
 'ZGF': 'Grand Forks',
 'ZGI': 'Gods River',
 'ZGR': 'Little Grand Rapids',
 'ZJG': 'Jenpeg',
 'ZJN': 'Swan River',
 'ZKE': 'Kashechewan',
 'YTD': 'Thicket Portage',
 'MSA': 'Muskrat Dam',
 'ZMH': '108 Mile',
 'PIW': 'Pikwitonei',
 'ZMT': 'Masset',
 'ZNG': 'Poplar River',
 'ZPB': 'Sachigo Lake',
 'ZPO': 'Pinehouse Lake',
 'ZRJ': 'Round Lake',
 'ZSJ': 'Sandy Lake',
 'ZSN': 'South Indian Lake',
 'ZST': 'Stewart',
 'ZTM': 'Shamattawa',
 'ZUC': 'Ignace',
 'ZUM': 'Churchill Falls',
 'ZWH': 'Lac Brochet',
 'ZWL': 'Wollaston Lake',
 'QLD': '',
 'BUJ': '',
 'BJA': 'Bejaia',
 'ALG': 'Algiers',
 'DJG': 'Djanet',
 'QFD': '',
 'VVZ': 'Illizi',
 'QSF': 'Setif',
 'TMR': 'Tamanrasset',
 'GJL': 'Jijel',
 'MZW': 'Mecheria',
 'QZN': '',
 'AAE': 'Annabah',
 'CZL': 'Constantine',
 'TEE': 'Tebessi',
 'BLJ': 'Batna',
 'HRM': '',
 'QDJ': '',
 'TID': 'Tiaret',
 'TIN': 'Tindouf',
 'QAS': '',
 'TAF': '',
 'TLM': 'Tlemcen',
 'ORN': 'Oran',
 'CBH': 'Bechar',
 'BFW': '',
 'MUW': '',
 'EBH': 'El Bayadh',
 'INF': 'In Guezzam',
 'BMW': 'Bordj Badji Mokhtar',
 'AZR': '',
 'BSK': 'Biskra',
 'ELG': '',
 'GHA': 'Ghardaia',
 'HME': 'Hassi Messaoud',
 'INZ': 'In Salah',
 'TGR': 'Touggourt',
 'LOO': 'Laghouat',
 'ELU': 'Guemar',
 'TMX': 'Timimoun',
 'OGX': 'Ouargla',
 'IAM': 'Amenas',
 'COO': 'Cotonou',
 'DJA': 'Djougou',
 'KDC': 'Kandi',
 'NAE': 'Natitingou',
 'PKO': 'Parakou',
 'SVF': 'Save',
 'XKY': 'Kaya',
 'OUG': 'Ouahigouya',
 'XDJ': 'Djibo',
 'XLU': 'Leo',
 'PUP': 'Po',
 'XBO': 'Boulsa',
 'XBG': 'Bogande',
 'DIP': 'Diapaga',
 'DOR': 'Dori',
 'FNG': "Fada N'gourma",
 'XGG': 'Gorom-Gorom',
 'XKA': 'Kantchari',
 'TMQ': 'Tambao',
 'XPA': 'Pama',
 'ARL': 'Arly',
 'XSE': 'Sebba',
 'TEG': 'Tenkodogo',
 'XZA': 'Zabre',
 'OUA': 'Ouagadougou',
 'BNR': 'Banfora',
 'DGU': 'Dedougou',
 'XGA': 'Gaoua',
 'XNU': 'Nouna',
 'BOY': 'Bobo Dioulasso',
 'TUQ': 'Tougan',
 'XDE': 'Diebougou',
 'XAR': 'Aribinda',
 'ACC': 'Accra',
 'TML': 'Tamale',
 'KMS': 'Kumasi',
 'NYI': 'Sunyani',
 'TKD': 'Sekondi-Takoradi',
 'ABJ': 'Abidjan',
 'OGO': 'Abengourou',
 'BXI': 'Boundiali',
 'BYK': '',
 'BQO': 'Bouna',
 'BDK': 'Bondoukou',
 'DIM': 'Dimbokro',
 'DJO': '',
 'FEK': 'Ferkessedougou',
 'GGN': 'Gagnoa',
 'GGO': 'Guiglo',
 'BBV': 'Grand-Bereby',
 'HGO': '',
 'MJC': '',
 'KEO': 'Odienne',
 'OFI': 'Ouango Fitini',
 'SEO': 'Seguela',
 'SPY': '',
 'ZSS': 'Sassandra',
 'TXU': 'Tabou',
 'ASK': 'Yamoussoukro',
 'ABV': 'Abuja',
 'AKR': 'Akure',
 'ABB': 'Asaba',
 'BNI': 'Benin',
 'CBQ': 'Calabar',
 'ENU': 'Enegu',
 'GMO': 'Gombe',
 'QUS': 'Gusau',
 'IBA': 'Ibadan',
 'ILR': 'Ilorin',
 'QOW': 'Owerri',
 'JOS': 'Jos',
 'KAD': 'Kaduna',
 'KAN': 'Kano',
 'MIU': 'Maiduguri',
 'MDI': 'Makurdi',
 'LOS': 'Lagos',
 'MXJ': 'Minna',
 'PHC': 'Port Harcourt',
 'SKO': 'Sokoto',
 'NBE': 'Enfidha',
 'YOL': 'Yola',
 'ZAR': 'Zaria',
 'MFQ': 'Maradi',
 'NIM': 'Niamey',
 'THZ': 'Tahoua',
 'AJY': 'Agadez',
 'ZND': 'Zinder',
 'TBJ': 'Tabarka',
 'MIR': 'Monastir',
 'TUN': 'Tunis',
 'OIZ': 'Sidi Ahmed',
 'GAF': 'Gafsa',
 'GAE': 'Gabes',
 'DJE': 'Djerba',
 'EBM': 'El Borma',
 'SFA': 'Sfax',
 'TOE': 'Tozeur',
 'LRL': 'Niamtougou',
 'LFW': 'Lome',
 'ANR': 'Antwerp',
 'BRU': 'Brussels',
 'CRL': 'Brussels',
 'KJK': 'Wevelgem',
 'LGG': 'Liege',
 'QNM': 'Namur',
 'OST': 'Ostend',
 'QHA': 'Hasselt',
 'OBL': 'Zoersel',
 'AOC': 'Altenburg',
 'HDF': 'Heringsdorf',
 'REB': 'Larz',
 'SXF': 'Berlin',
 'CSO': 'Magdeburg',
 'BBH': '',
 'ZMG': 'Magdeburg',
 'CBU': 'Cottbus',
 'GTI': 'Rugen',
 'PEF': 'Peenemunde',
 'DRS': 'Dresden',
 'ERF': 'Erfurt',
 'FRA': 'Frankfurt-am-Main',
 'FMO': 'Munster',
 'HAM': 'Hamburg',
 'THF': 'Berlin',
 'CGN': 'Cologne',
 'DUS': 'Dusseldorf',
 'MUC': 'Munich',
 'NUE': 'Nuremberg',
 'LEJ': 'Leipzig',
 'SCN': 'Saarbrucken',
 'STR': 'Stuttgart',
 'TXL': 'Berlin',
 'HAJ': 'Hannover',
 'BRE': 'Bremen',
 'QEF': 'Egelsbach',
 'HHN': 'Hahn',
 'MHG': 'Mannheim',
 'QMZ': 'Mainz',
 'SGE': '',
 'XFW': 'Hamburg',
 'KEL': 'Kiel',
 'LBC': 'Lubeck',
 'EUM': 'Neumunster',
 'FMM': 'Memmingen',
 'AAH': 'Aachen',
 'BNJ': 'Bonn',
 'ESS': '',
 'BFE': 'Bielefeld',
 'ZOJ': 'Marl',
 'MGL': 'Monchengladbach',
 'PAD': 'Paderborn',
 'NRN': 'Weeze',
 'DTM': 'Dortmund',
 'AGB': 'Augsburg',
 'OBF': '',
 'RBM': 'Straubing',
 'FDH': 'Friedrichshafen',
 'FRF': 'Oschersleben',
 'SZW': '',
 'BYU': 'Bayreuth',
 'QOB': 'Ansbach',
 'HOQ': 'Hof',
 'BBJ': 'Bitburg',
 'ZQW': 'Zweibrucken',
 'FKB': 'Baden-Baden',
 'ZQL': 'Donaueschingen',
 'LHA': '',
 'BWE': '',
 'KSF': 'Kassel',
 'BRV': 'Bremerhaven',
 'XLW': 'Lemwerder',
 'EME': 'Emden',
 'AGE': 'Wangerooge',
 'WVN': 'Wilhelmshaven',
 'JUI': 'Juist',
 'LGO': 'Langeoog',
 'ZOW': 'Klausheide',
 'BMK': 'Borkum',
 'NOD': 'Norddeich',
 'VAC': 'Cloppenburg',
 'NRD': 'Norderney',
 'BMR': 'Baltrum',
 'HEI': 'Busum',
 'FLF': 'Flensburg',
 'HGL': 'Helgoland',
 'PSH': 'Sankt Peter-Ording',
 'GWT': 'Westerland',
 'OHR': 'Wyk auf Fohr',
 'KDL': 'Kardla',
 'URE': 'Kuressaare',
 'EPU': 'Parnu',
 'TLL': 'Tallinn',
 'TAY': 'Tartu',
 'ENF': 'Enontekio',
 'QVE': 'Forssa',
 'KEV': 'Halli / Kuorevesi',
 'HEM': 'Helsinki',
 'HEL': 'Helsinki',
 'HYV': '',
 'KTQ': '',
 'IVL': 'Ivalo',
 'JOE': 'Joensuu / Liperi',
 'JYV': 'Jyvaskylan Maalaiskunta',
 'KAU': 'Kauhava',
 'KEM': 'Kemi / Tornio',
 'KAJ': 'Kajaani',
 'KHJ': '',
 'KOK': 'Kokkola / Kruunupyy',
 'KAO': 'Kuusamo',
 'KTT': 'Kittila',
 'KUO': 'Kuopio / Siilinjarvi',
 'QLF': '',
 'LPP': 'Lappeenranta',
 'MHQ': '',
 'MIK': 'Mikkeli',
 'OUL': 'Oulu / Oulunsalo',
 'POR': 'Pori',
 'RVN': 'Rovaniemi',
 'SVL': 'Savonlinna',
 'SJY': 'Seinajoki / Ilmajoki',
 'SOT': 'Sodankyla',
 'TMP': 'Tampere / Pirkkala',
 'TKU': 'Turku',
 'UTI': 'Utti / Valkeala',
 'VAA': 'Vaasa',
 'VRK': 'Varkaus / Joroinen',
 'YLI': '',
 'BFS': 'Belfast',
 'ENK': 'Enniskillen',
 'BHD': 'Belfast',
 'LDY': 'Derry',
 'BHX': 'Birmingham',
 'CVT': 'Coventry',
 'GLO': 'Staverton',
 'ORM': 'Northampton',
 'NQT': 'Nottingham',
 'MAN': 'Manchester',
 'DSA': 'Doncaster',
 'UPV': 'Upavon',
 'LYE': 'Lyneham',
 'DGX': 'St. Athan',
 'YEO': 'Yeovil',
 'CAL': 'Campbeltown',
 'EOI': 'Eday',
 'FIE': 'Fair Isle',
 'WHS': 'Whalsay',
 'COL': 'Coll Island',
 'NRL': 'North Ronaldsay',
 'OBN': 'North Connel',
 'PPW': 'Papa Westray',
 'SOY': 'Stronsay',
 'NDY': 'Sanday',
 'LWK': 'Lerwick',
 'WRY': 'Westray',
 'CSA': 'Colonsay',
 'HAW': 'Haverfordwest',
 'CWL': 'Cardiff',
 'SWS': 'Swansea',
 'BRS': 'Bristol',
 'LPL': 'Liverpool',
 'LTN': 'London',
 'LEQ': "Land's End",
 'PLH': 'Plymouth',
 'ISC': "St. Mary's",
 'BOH': 'Bournemouth',
 'SOU': 'Southampton',
 'BBP': 'Bembridge',
 'QLA': 'Lasham',
 'NQY': 'Newquay',
 'QUG': 'Chichester',
 'ACI': 'Saint Anne',
 'GCI': 'Saint Peter Port',
 'JER': 'Saint Helier',
 'ESH': 'Brighton',
 'BQH': 'London',
 'LGW': 'London',
 'KRH': 'Redhill',
 'LCY': 'London',
 'FAB': 'Farnborough',
 'BBS': 'Yateley',
 'LHR': 'London',
 'SEN': 'Southend',
 'LYX': 'Lydd',
 'MSE': 'Manston',
 'CAX': 'Carlisle',
 'BLK': 'Blackpool',
 'HUY': 'Grimsby',
 'BWF': 'Barrow-in-Furness',
 'LBA': 'Leeds',
 'CEG': 'Hawarden',
 'IOM': 'Castletown',
 'NCL': 'Newcastle',
 'MME': 'Durham',
 'EMA': 'Nottingham',
 'HLY': 'Angelsey',
 'KOI': 'Orkney Islands',
 'LSI': 'Lerwick',
 'WIC': 'Wick',
 'ABZ': 'Aberdeen',
 'INV': 'Inverness',
 'GLA': 'Glasgow',
 'EDI': 'Edinburgh',
 'ILY': 'Port Ellen',
 'PIK': 'Glasgow',
 'BEB': 'Balivanich',
 'SCS': 'Shetland Islands',
 'DND': 'Dundee',
 'SYY': 'Stornoway',
 'BRR': 'Eoligarry',
 'PSL': 'Perth',
 'TRE': 'Balemartine',
 'UNT': 'Shetland Islands',
 'BOL': 'Ballykelly',
 'FSS': 'Kinloss',
 'ADX': 'St. Andrews',
 'LMO': 'Lossiemouth',
 'CBG': 'Cambridge',
 'NWI': 'Norwich',
 'STN': 'London',
 'QFO': 'Duxford',
 'HYC': 'High Wycombe',
 'EXT': 'Exeter',
 'FZO': 'Bristol',
 'OXF': 'Kidlington',
 'RCS': 'Rochester',
 'BEX': 'Benson',
 'LKZ': 'Lakenheath',
 'MHZ': 'Mildenhall',
 'QUY': 'St. Ives',
 'FFD': 'Fairford',
 'BZZ': 'Brize Norton',
 'ODH': 'Odiham',
 'WXF': 'Wethersfield',
 'NHT': 'London',
 'QCY': 'Coningsby',
 'BEQ': 'Thetford',
 'OKH': 'Cottesmore',
 'SQZ': 'Scampton',
 'HRT': 'Linton-On-Ouse',
 'WTN': 'Waddington',
 'MRH': 'Marham',
 'MPN': 'Mount Pleasant',
 'AMS': 'Amsterdam',
 'MST': 'Maastricht',
 'QAR': 'Arnhem',
 'EIN': 'Eindhoven',
 'GRQ': 'Groningen',
 'GLZ': 'Breda',
 'DHR': 'Den Helder',
 'LEY': 'Lelystad',
 'LWR': 'Leeuwarden',
 '---': '',
 'RTM': 'Rotterdam',
 'ENS': 'Enschede',
 'UDE': 'Uden',
 'WOE': 'Bergen Op Zoom',
 'BYT': 'Bantry',
 'BLY': 'Belmullet',
 'NNR': 'Inverin',
 'CLB': 'Castlebar',
 'WEX': 'Wexford',
 'ORK': 'Cork',
 'GWY': 'Galway',
 'CFN': 'Donegal',
 'DUB': 'Dublin',
 'IOR': 'Inis Mor',
 'INQ': 'Inis Oirr',
 'KKY': 'Kilkenny',
 'NOC': 'Charleston',
 'KIR': 'Killarney',
 'LTR': 'Letterkenny',
 'IIA': 'Inis Meain',
 'SNN': 'Shannon',
 'SXL': 'Sligo',
 'WAT': 'Waterford',
 '0': 'Tesouro',
 'AAR': 'Aarhus',
 'BLL': 'Billund',
 'CPH': 'Copenhagen',
 'EBJ': 'Esbjerg',

In [38]:
len(dicc)

6578

In [25]:
type(book['arr_port'][0])

str

In [26]:
type(datas['iata'][2])

str

In [39]:
#Por fin he entendido el problema y es que el string esta mal el book^arr_port ya que tiene una separacion muy grande.
new = book["arr_port"].str.split(" ", n = 1, expand = True)

In [40]:
new[0][0]

'LHR'

In [41]:
book["iata"] = new[0]

In [30]:
book['city'] = book['iata'].map(dicc)

In [31]:
book['city'].head(5)

0       London
1    Charlotte
2    Charlotte
3       Moscow
4       Moscow
Name: city, dtype: object

In [32]:
book['city'].value_counts()

London         247111
New York       221142
Paris          212250
Los Angeles    143220
Dubai          135640
                ...
Kryvyi Rih         10
Rayong             10
Jiamusi            10
Petersburg         10
Changde            10
Name: city, Length: 2021, dtype: int64

In [ ]:
#Ya caso lo tenemos, solo queda meterlo en el groupby y ya esta el ejercicio 2 completo